---
- name: stop service
  hosts: "{{ host }}"
  remote_user: ubuntu
  become: yes
  connection: ssh
  gather_facts: yes

  tasks:
    - name: Stop Apache Service
      service:
        name: apache2
        state: started
    

